name: clean_ui
description: Build user interfaces easily and consistently with extensible and customizable components.
version: 1.0.4

homepage: https://github.com/guilhermetog/clean_ui

environment:
  sdk: ">=3.7.2 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^5.1.1
  test: ^1.24.0

flutter: