name: ui_components
description: Build user interfaces easily and consistently with customizable components.
version: 1.0.0

homepage: https://github.com/seu_usuario/ui_components

environment:
  sdk: ">=3.7.2 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^5.0.0
  test: ^1.24.0

flutter: