name: CI Publish Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Flutter 3.29.3 manually
        run: |
          git clone https://github.com/flutter/flutter.git --branch stable --depth 1
          ./flutter/bin/flutter --version
          echo "$PWD/flutter/bin" >> $GITHUB_PATH

      - name: Pre-cache Flutter dependencies
        run: flutter precache

      - name: Install dependencies
        run: flutter pub get

      - name: Run analyze
        run: flutter analyze

      - name: Run tests
        run: flutter test --no-pub

      - name: Dry-run publish check
        run: dart pub publish --dry-run
