name: CI Publish Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.1'
          channel: 'stable'

      - name: Pre-cache Flutter dependencies
        run: flutter precache

      - name: Install dependencies
        run: flutter pub get

      - name: Run analyze
        run: flutter analyze lib test


      - name: Run tests
        run: flutter test --no-pub

      - name: Dry-run publish check
        run: dart pub publish --dry-run
